### ISSUE TITLE
Plugin does not infer type if using 'prop-types' package.

### ISSUE THREAD

**Issue by matt961** [dxinteractive/jsdoc-react-proptypes#2]
```
import PropTypes from 'prop-types'
...
MyComponent.propTypes = {
	/**
	 *	Is the user logged in?
	 */
	isLoggedIn: PropTypes.bool,

	/**
	 *	Callback to handle submitted login input.
	 *	@callback
	 */
	handleSubmittedLogin: PropTypes.func,
	loginInput: PropTypes.shape({
		username: PropTypes.string,
		password: PropTypes.string
	})
};
```
Outputs:
![image](https://user-images.githubusercontent.com/11224476/31095271-20c2ba5a-a76d-11e7-8a59-8350621aed5a.png)

Using React.PropTypes was deprecated according to the React docs, so I'm wondering if there are plans to make the `prop-types` package work with this plugin?

**Comment by bartvde** [comment]
just noticed this as well

**Comment by dxinteractive** [comment]
As much as I'd like to help, at this point I don't really have plans no. I'm not a fan of jsdoc and am moving away from using it personally. That said I'm more than happy to take PRs.

**Comment by bartvde** [comment]
did you ever consider using ```react-docgen``` for this jsdoc plugin?

**Comment by bartvde** [comment]
@dxinteractive what documentation system did you move to btw?

**Comment by bartvde** [comment]
I went with this approach: it's basically a new plugin making use of ```react-docgen```:

```
var reactDocs = require('react-docgen');
var fs = require('fs');

const componentInfo = {};

exports.handlers = {
    fileBegin: function(e) {
      const filename = e.filename;
      if (filename.indexOf('component') !== -1) {
        filename.substr(filename.indexOf('src/')+4, filename.indexOf('.js')-(filename.indexOf('src/')+4));
        const start = filename.indexOf('src/') + 4;
        const end = filename.indexOf('.js') - start;
        const module = `module:${e.filename.substr(start, end)}`;
        componentInfo[module] = reactDocs.parse(fs.readFileSync(e.filename), reactDocs.resolver.findAllComponentDefinitions);
      }
    },
    newDoclet: function(e) {
      if (e.doclet ){
        const doclet = e.doclet;
        const info = componentInfo[doclet.longname];
        if (info) {
          doclet.properties = [];
          for (var key in info[0].props) {
            const prop = info[0].props[key];
            doclet.properties.push({
              name: key,
              description: prop.description,
              defaultvalue: prop.defaultValue ? prop.defaultValue.value : undefined,
              type: {names: prop.type ? [prop.type.name] : undefined}
            });
          }
        }
      }
    }
};
```

**Comment by arronhunt** [comment]
Is it safe to assume that this project is no longer being maintained? @dxinteractive

**Comment by bartvde** [comment]
FYI I've worked more on my plugin and it can be found here: https://github.com/boundlessgeo/sdk/blob/master/docs/proptype-plugin.js

**Comment by dxinteractive** [comment]
@arronhunt yes, sorry. I'll add a note to the readme.

@bartvde None yet. For the particular projects I was using this one, I ended up finding it easier to write docs by hand and get all the easy customisation that comes with. We're generating prop types from flow types now using one of the `babel-plugin-flow-react-proptypes`. For docs we have vague plans to use esprima directly and write something around it that can infer type information from flow types, and hook comments in there too, outputting a big nested data shape that can be used by something else to do the rendering. I think jsdoc would benefit from that split of responsibilities. It would be a cool project, but docs are a low priority right now.

**Comment by filipef101** [comment]
How can I use it now then? any possible light up?
